-- Sample data for Incident Management Application
-- This script inserts test data for development/testing

-- Insert sample incidents
INSERT INTO incidents (title, description, severity, status, reporter_name, reporter_email, assigned_to, resolution, created_date, updated_date) VALUES
('Order not displayed', 'Customer have create a new order but its not displayed on order UI', 'HIGH', 'RESOLVED', 'John Doe', 'john.doe@example.com', 'N3 OMS', 'Order at CREATED status are not displayed in frontend. Payment linked to order need to be completed in order to shift order to PENDING status', '2023-10-01', '2023-10-01'),
('System Performance Issue', 'The application is running slowly during peak hours', 'HIGH', 'RESOLVED', 'Jane Smith', 'jane.smith@example.com', 'N3 OMS', 'We fix an issue on one on the most used endpoints of the order API that was not quite well develop to handle spikes in charge', '2023-10-02', '2023-10-03'),
('Cannot move forward an order', 'When I click on move forward button, order is not move forward and I don''t know why', 'MEDIUM', 'RESOLVED', 'Alice Brown', 'alice.brown@example.com', 'N3 Payment', 'Payment status was not updated as we never received payment ackowledge from customer bank; After verification, we force payment status to COMPLETED in order to unblock the move forward function on this order', '2023-10-04', '2023-10-05'),
('Database Connection Timeout', 'Intermittent database connection issues', 'MEDIUM', 'RESOLVED', 'Alice Brown', 'alice.brown@example.com', 'Database Team', 'Increased connection pool size', '2023-10-04', '2023-10-05'),
('Payment Processing Inconsistency', 'Order #3 (Eric Dupont) shows SHIPPED status but payment remains PENDING, creating business state inconsistency', 'HIGH', 'RESOLVED', 'Eric Dupont', 'eric.dupont@example.com', 'N3 Payment', 'Identified missing payment record for $300.00 order. Created new payment entry (Payment ID: 5) with COMPLETED status dated 2023-10-07. Verified payment processing workflow and implemented additional validation to prevent future payment-order state mismatches.', '2025-01-05', '2025-01-06'),
('Failed Payment Retry Mechanism', 'Payment retry function is not working correctly when payment fails and cannot be retried automatically', 'MEDIUM', 'RESOLVED', 'Operations Team', 'ops.team@example.com', 'N3 Payment', 'Established new procedure: when a payment cannot be retried through automated retry function, create a new payment record with same details and mark the original failed payment as obsolete. This ensures proper audit trail while allowing business continuity. Updated documentation and training for operations team.', '2023-10-08', '2023-10-08'),
('UI Display Bug', 'Buttons are not aligned properly on mobile devices', 'LOW', 'CLOSED', 'Charlie Davis', 'charlie.davis@example.com', 'N3 OMS', 'Fixed CSS styling issues', '2023-10-05', '2023-10-06'),
('New order that I cannot move forward', 'Jean Bonbeur have put a new order in the system, but I cannot see it in the system in order to prepare it for shipment', 'HIGH', 'OPEN', 'Alice Brown', 'alice.brown@example.com', '', null, '2025-05-05', '2025-05-05');
